-- 047: application passwords.
--
-- A device profile has to carry a credential in the clear — .mobileconfig has
-- no way to encrypt one, and neither does any IMAP client's account setup. Up
-- to now that credential could only be the account password itself, which puts
-- the keys to the web UI into a file that lands in Downloads, gets AirDropped,
-- and is backed up by whatever the phone syncs to. Revoking it meant changing
-- the password everywhere.
--
-- An application password is a second credential for the same user that works
-- on the protocol endpoints (IMAP, SMTP, CalDAV, CardDAV) and NOWHERE ELSE.
-- It is explicitly rejected by the web and desktop logins: a credential that
-- can reach the UI can mint more of itself and read the others, which is the
-- opposite of a scoped credential. Losing one costs a single revoke.
--
-- Applied manually via psql (RunMigrations is a no-op).

CREATE TABLE IF NOT EXISTS app_passwords (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Human label: "iPhone", "iPad Мария", "Thunderbird дома". This is the
    -- only thing distinguishing two rows in the UI, since the secret itself
    -- is never shown again after creation.
    label VARCHAR(255) NOT NULL DEFAULT '',

    -- SHA-256 of the normalised secret, hex. Deliberately NOT bcrypt.
    --
    -- The secret is generated by us: 16 random letters, ~75 bits. There is no
    -- dictionary to attack and no human-chosen password to protect, so the
    -- work factor bcrypt exists to provide buys nothing here. What it would
    -- cost is real: CalDAV clients send Basic Auth on *every* PROPFIND, and a
    -- per-request bcrypt — times however many app passwords the user holds,
    -- since a slow hash cannot be looked up by value — turns a calendar poll
    -- into a CPU load. A fast hash is indexable, so verification is one row.
    token_sha256 CHAR(64) NOT NULL,

    -- Last four characters of the secret, for telling rows apart in the UI.
    -- Not sensitive on its own and not enough to narrow a guess meaningfully.
    last4 VARCHAR(4) NOT NULL DEFAULT '',

    created_at BIGINT NOT NULL DEFAULT 0,

    -- Throttled: written at most once a minute per row, so a client polling
    -- CalDAV every few seconds doesn't turn every read into a write.
    last_used_at BIGINT NOT NULL DEFAULT 0,

    -- NULL means active. Revoked rows are kept rather than deleted so the list
    -- can still show that a credential existed and when it stopped working.
    revoked_at BIGINT
);

-- Verification looks up (user_id, token_sha256) directly — no scan, no
-- iteration over the user's other passwords.
CREATE UNIQUE INDEX IF NOT EXISTS idx_app_passwords_token
    ON app_passwords(token_sha256);

CREATE INDEX IF NOT EXISTS idx_app_passwords_user
    ON app_passwords(user_id, created_at DESC);
