fn main() {
    slint_build::compile("ui/app.slint").unwrap();
    // WebKitGTK / GTK / Cairo are pulled in through pkg-config via their
    // respective crates' build scripts — no extra wiring needed here.

    // Windows: embed the app icon (Explorer / taskbar / Alt-Tab). The ico is
    // generated by installer/make_icon.ps1.
    #[cfg(windows)]
    {
        let mut res = winresource::WindowsResource::new();
        res.set_icon("assets/ddmail.ico");
        res.compile().expect("embedding ddmail.ico failed");
    }
}
