fn main() {
    slint_build::compile("ui/app.slint").unwrap();
    // WebKitGTK / GTK / Cairo are pulled in through pkg-config via their
    // respective crates' build scripts — no extra wiring needed here.

    // Build identity for the tray tooltip: git hash ('+' = dirty tree) and
    // the commit date. Kills the «какой это бинарь?» class of confusion —
    // the installed build and a fresh target/release become tellable apart.
    // Re-stamped when HEAD moves (commit / checkout / pull); uncommitted
    // edits keep the previous stamp but carry the '+' marker.
    println!("cargo:rerun-if-changed=../../.git/HEAD");
    println!("cargo:rerun-if-changed=../../.git/refs/heads/main");
    let git = |args: &[&str]| {
        std::process::Command::new("git")
            .args(args)
            .output()
            .ok()
            .filter(|o| o.status.success())
            .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
    };
    let hash = git(&["rev-parse", "--short", "HEAD"]).unwrap_or_else(|| "unknown".into());
    let dirty = git(&["status", "--porcelain", "-uno"])
        .map(|s| !s.is_empty())
        .unwrap_or(false);
    let date = git(&["log", "-1", "--date=format:%Y-%m-%d %H:%M", "--format=%cd"])
        .unwrap_or_default();
    println!(
        "cargo:rustc-env=BUILD_GIT={}{}{}",
        hash,
        if dirty { "+" } else { "" },
        if date.is_empty() { String::new() } else { format!(" · {date}") },
    );

    // Windows: embed the app icon (Explorer / taskbar / Alt-Tab). The ico is
    // generated by installer/make_icon.ps1.
    #[cfg(windows)]
    {
        let mut res = winresource::WindowsResource::new();
        res.set_icon("assets/ddmail.ico");
        res.compile().expect("embedding ddmail.ico failed");
    }
}
